#!/usr/bin/env node
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import { readFile, writeFile, chmod } from 'node:fs/promises';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');

const SHEBANG = '#!/usr/bin/env node\n';
const REQUIRE_SHIM =
  `import { createRequire as __cursedCreateRequire } from 'node:module';\n` +
  `const require = __cursedCreateRequire(import.meta.url);\n`;

// ROI-61: regenerate the inlined-prompts map BEFORE esbuild so the
// committed `scripts/lib/prompts-inlined.gen.mjs` (which the bundled
// worker imports for filesystem-free prompt loading) stays in lockstep
// with `prompts/*.md`. `build:check` then enforces it in CI alongside
// the bundle artifacts.
//
// Keys are CommandName ("advise" | "review" | "review-plan" | "delegate")
// and intentionally explicit — `review-plan` points at the historical
// `plan-review.md` filename. Adding a new command means adding an entry
// here AND a prompts/*.md file.
/** @type {Record<string, string>} */
const COMMAND_PROMPT_FILES = {
  advise: 'advise.md',
  delegate: 'delegate.md',
  review: 'review.md',
  'review-plan': 'plan-review.md',
};

/** @type {Record<string, string>} */
const inlinedPrompts = {};
for (const [command, file] of Object.entries(COMMAND_PROMPT_FILES)) {
  inlinedPrompts[command] = await readFile(join(repoRoot, 'prompts', file), 'utf8');
}
const promptsGenPath = join(repoRoot, 'scripts/lib/prompts-inlined.gen.mjs');
const promptsGenBody =
  `// AUTO-GENERATED by scripts/build.mjs from prompts/*.md — do not edit by hand.\n` +
  `// Run \`npm run build\` to regenerate; \`build:check\` enforces this file matches\n` +
  `// the on-disk prompts in CI. Keyed by CommandName so the bundled worker can\n` +
  `// resolve prompts without touching the filesystem (ROI-61).\n` +
  `\n` +
  `/** @type {Record<import('./types.d.ts').CommandName, string>} */\n` +
  `export const PROMPTS = ${JSON.stringify(inlinedPrompts, null, 2)};\n`;
await writeFile(promptsGenPath, promptsGenBody);

/** @type {import('esbuild').BuildOptions} */
const common = {
  bundle: true,
  platform: 'node',
  target: 'node20',
  format: 'esm',
  legalComments: 'none',
  logLevel: 'info',
};

// esbuild emits source-path comments and __commonJS registry keys whose
// `node_modules/...` prefix is rendered relative to the build cwd. When the
// build is invoked from a git worktree without its own `node_modules`, the
// prefix gains one or more `../` segments. Strip those so the bundle output
// is byte-stable regardless of where it was built — otherwise `build:check`
// (a `git diff --exit-code` against committed bundles) trips in CI.
const NODE_MODULES_REL = /(\.\.\/)+node_modules\//g;

const entries = [
  {
    in: join(repoRoot, 'scripts/mcp/cursed-mcp.mjs'),
    out: join(repoRoot, 'scripts/mcp/cursed-mcp.bundled.mjs'),
  },
  {
    in: join(repoRoot, 'scripts/cursed-job.mjs'),
    out: join(repoRoot, 'scripts/cursed-job.bundled.mjs'),
  },
];

for (const { in: entry, out } of entries) {
  await build({ ...common, entryPoints: [entry], outfile: out });
  // esbuild preserves the source shebang at line 1. Replace it with a header
  // that adds the createRequire shim so transitive CJS deps that call
  // `require('node:stream')` etc. resolve at runtime.
  let body = await readFile(out, 'utf8');
  if (body.startsWith('#!')) body = body.slice(body.indexOf('\n') + 1);
  body = body.replace(NODE_MODULES_REL, 'node_modules/');
  await writeFile(out, SHEBANG + REQUIRE_SHIM + body);
  await chmod(out, 0o755);
}

// Mirror package.json version into the two plugin-manifest files so the
// Claude Code-facing identifiers and the npm-style version stay in lockstep.
// Runs every build, so contributors and the release pipeline (which calls
// `npm run build` via @semantic-release/exec after @semantic-release/npm
// bumps package.json) both keep these aligned.
const pkg = JSON.parse(await readFile(join(repoRoot, 'package.json'), 'utf8'));
for (const file of ['.claude-plugin/plugin.json', '.claude-plugin/marketplace.json']) {
  const path = join(repoRoot, file);
  const obj = JSON.parse(await readFile(path, 'utf8'));
  if (obj.version !== pkg.version) {
    obj.version = pkg.version;
    await writeFile(path, `${JSON.stringify(obj, null, 2)}\n`);
  }
}
