import { describe, it, expect } from 'vitest';
import { readFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PROMPTS } from '../../scripts/lib/prompts-inlined.gen.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..', '..');

// `prompts-inlined.gen.mjs` is regenerated by `scripts/build.mjs` and
// consumed by both the source-tree run.mjs and the bundled worker
// (ROI-61). These tests assert that the committed gen file stays in
// lockstep with prompts/*.md and that every CommandName resolves.

/** @type {Record<import('../../scripts/lib/types.d.ts').CommandName, string>} */
const EXPECTED_FILES = {
  advise: 'advise.md',
  delegate: 'delegate.md',
  review: 'review.md',
  'review-plan': 'plan-review.md',
};

describe('PROMPTS (inlined gen module)', () => {
  it('contains an entry for every CommandName', () => {
    expect(Object.keys(PROMPTS).sort()).toEqual(Object.keys(EXPECTED_FILES).sort());
  });

  it('every entry is a non-empty string', () => {
    for (const [name, body] of Object.entries(PROMPTS)) {
      expect(typeof body, `PROMPTS["${name}"] must be a string`).toBe('string');
      expect(body.length, `PROMPTS["${name}"] must be non-empty`).toBeGreaterThan(0);
    }
  });

  it('matches prompts/*.md byte-for-byte (stale gen file would regress bundled worker)', async () => {
    for (const [command, file] of Object.entries(EXPECTED_FILES)) {
      const onDisk = await readFile(join(repoRoot, 'prompts', file), 'utf8');
      const inlined = PROMPTS[/** @type {import('../../scripts/lib/types.d.ts').CommandName} */ (command)];
      expect(inlined, `PROMPTS["${command}"] is stale vs prompts/${file}`).toBe(onDisk);
    }
  });
});
